### ISSUE TITLE
Some issues when try to generate SDK code

### ISSUE THREAD

**Issue by msyyc** [bterlson/typespec-todo#13]
When trying to generate SDK code with https://github.com/bterlson/typespec-todo/blob/main/main.tsp, I meet the following error:
![image](https://github.com/user-attachments/assets/487aa4d4-c35f-4df3-b6ea-b12baa4c0abd)

I also find some other issues:
- Since this repo is for unbranded demo, the dependencies about emitter shall be `@typespec/http-client-xxx` instead of `@azure-tools/typespec-python`?
- TCGC is 0.40.0 which is incompatible with latest language emitter.

**Comment by msyyc** [comment]
I heard from @lirenhe that this repo will be used to demo unbranded so tried locally then find up issues.

**Comment by lirenhe** [comment]
@msyyc, the compile issue should be resolved and please also update emitter name as shown in this PR:  https://github.com/bterlson/typespec-todo/pull/15
